In [31]:
from sklearn.linear_model import LinearRegression as lr
import pandas as pd
df=pd.read_csv("C:/Users/Benji/Desktop/Empty Folder/elect80.csv")

,FIPS,long,lat,pc_turnout,pc_college,pc_homeownership,pc_income
count,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000
mean,30712.852591,-91.638847,38.281092,0.572593,0.490358,0.364645,8.552081
std,14982.781877,11.475691,4.838502,0.108013,0.101735,0.044410,1.648232
min,1001.000000,-124.229900,25.117067,0.047026,0.208681,0.029579,4.322441
25%,19050.000000,-98.025277,34.687437,0.496615,0.408039,0.343214,7.415863
50%,29217.000000,-90.171689,38.327049,0.567892,0.504557,0.373433,8.394631
75%,46014.000000,-83.369519,41.691116,0.642946,0.566470,0.395074,9.514892
max,56045.000000,-67.609990,48.833747,1.105263,0.846647,0.456749,24.962025

In [35]:
df=df[df.pc_turnout <= 1]

,FIPS,long,lat,pc_turnout,pc_college,pc_homeownership,pc_income
count,3106.000000,3106.000000,3106.000000,3106.000000,3106.000000,3106.000000,3106.000000
mean,30720.148100,-91.633811,38.281240,0.572421,0.490269,0.364657,8.551461
std,14979.673849,11.474104,4.839274,0.107607,0.101631,0.044411,1.648136
min,1001.000000,-124.229900,25.117067,0.047026,0.208681,0.029579,4.322441
25%,19051.500000,-98.014335,34.687035,0.496597,0.407956,0.343245,7.415818
50%,29218.000000,-90.153773,38.331493,0.567891,0.504536,0.373444,8.394240
75%,46014.500000,-83.367770,41.691184,0.642751,0.566428,0.395081,9.513973
max,56045.000000,-67.609990,48.833747,0.956446,0.846647,0.456749,24.962025

In [34]:
cols=list(df.columns)
cols.remove("FIPS")
cols.remove("pc_income")
predictor = lr()
f=predictor.fit(X=df[cols], y=df["pc_income"])
f.predict(df[cols])[1]

9.209011590352643